import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/globals.css";
import "../css/responsive.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/backgroundMain.webp"
          as="image"
          type="image/webp"
        />
        {/* <link
          rel="preload"
          href="/random_center_bg.webp"
          as="image"
          type="image/webp"
        /> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
