import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/globals.css";
import "../css/responsive.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {" "}
      <head>
        {/* Preload the background image */}
        <link
          rel="preload"
          href="/backgroundMain.webp" // Path to your background image
          as="image"
          type="image/webp"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
